Ext.define('Wsitms.view.base.PropForm',{
	extend:'Ext.window.Window',
	xtype:'prop-form',
	height:'560',
	width:400,
	bind:{
		title:'{title}'
	},
	modal:true,//模态框，开启遮罩
	items:{
	xtype:'form',
	reference:'propForm',
    layout:{
    	type:'vbox',
    	align:'center'
    },
	items:[{
		xtype:'textfield',
		fieldLabel:'自动生成属性编号',
		name:'PROPERTY_ID',
		hidden:true,
		reference:'primary_id',
		bind:'{id}'
	},{
		xtype:'textfield',
		fieldLabel:'用户定义属性编号',
		name:'PROPERTYNO',
		allowBlank:false,
		blankText:'属性编号不能为空',
		msgTarget:'side',//设置不符合验证的提示方式
		regex:/^[(A-Za-z0-9]{2,10}$/,
		regexText:'属性编号必须由2-10的数字和字母组成',
	},{
		xtype:'textfield',
		fieldLabel:'属性名称',
		name:'PROPERTYNAME',
		allowBlank:false,
		blankText:'属性名称不能为空',
		msgTarget:'side',
		regex:/^[(\u4e00-\u9fa5)|A-Za-z0-9]{2,10}$/,
		regexText:'属性名称必须由2-10的汉字或数字或字母组成',
	},{
		xtype:'textfield',
		fieldLabel:'属性操作',
		name:'PROPERTYOP',
		regex:/^([\u4e00-\u9fa5]{2,10})|([A-Za-z0-9]{4,20})$/,
		regexText:'属性操作必须由的汉字或数字或字母组成,长度不能超过10',
		msgTarget:'side',
	},{
		xtype:'combobox',
		fieldLabel:'属性标志',
		name:'PROPERTYMARK',
		editable:false,
		queryMode:'local',
		displayField: 'name',
		valueField:'abbr',
		allowBlank:false,
		blankText:'属性标志不能为空',
		msgTarget:'side',
		store:{data:[{
			'abbr':'OP','name':'OP'
		},{
			'abbr':'PSWD','name':'PSWD'
		}]},
	},{
		xtype:'combobox',
		fieldLabel:'属性取值类型',
		name:'PROPERTYVALUETYPE',
		editable:false,
		queryMode:'local',
		allowBlank:false,
		blankText:'属性标志不能为空',
		msgTarget:'side',
		displayField: 'name',
		valueField:'abbr',
		store:{data:[{
			'abbr':'CHAR','name':'CHAR'
		},{
			'abbr':'NUMBER','name':'NUMBER'
		}]},
	},{
		xtype:'textfield',
		fieldLabel:'属性正常取值',
		name:'PROPERTYCHAR',
/*		blankText:'属性正常取值不能为空',
		msgTarget:'side',
		allowBlank:false,*/
	},{
		xtype:'textfield',
		fieldLabel:'最小正常值',
		name:'PROPERTYMINI',
/*		blankText:'最小正常值不能为空',
		msgTarget:'side',
		allowBlank:false,*/
	},{
		xtype:'textfield',
		fieldLabel:'最大正常值',
		name:'PROPERTYMAX',
/*		blankText:'最大正常值不能为空',
		msgTarget:'side',
		allowBlank:false,*/
	},{
		xtype:'textarea',
		fieldLabel:'备注',
		name:'NOTE',
	},{
		xtype:'checkboxfield',
		fieldLabel:'图形显示',
		name:'SHOWMARK',
		inputValue:'Y',
		boxLabel:'是',
		margin:'0 100 0 0'
	}],
	},
	buttons:[{
		text:'保存',
		handler:'saveForm'
	},{
		text:'清空',
		handler:'resetForm',
		reference:'propFormReset'
	},{
		text:'返回',
		handler:'closeForm'
	}]
})
