Ext.define('Wsitms.view.base.QueryLog',{
	extend:'Ext.panel.Panel',
	xtype:'query-log',
	layout:'vbox',//布局可以激活百分比
	items:[{
		title:'日志信息',
		xtype:'grid',
		style:'margin-top:2px',
		height:'60%',
		width:'100%',
		tbar:[{
			text:'查询',
			handler:''
		}],
		columns:[{
			text:'用户编号',
			dataIndex:''
		},{
			text:'用户名称',
			dataIndex:''
		},{
			text:'登陆时间',
			dataIndex:''
		}],
		bbar:{
		    xtype:'pagingtoolbar',
    	    displayInfo:true,//显示信息
    	    displayMsg : '显示:{0}-{1}条,总共:{2}条',//显示格式,0表示start 1表示end 2表示total
    	    emptyMsg:'没有需要显示的数据' 
		},
		selModel:{
			selType:'checkboxmodel'
		}
	},{
		xtype:'grid',
		title:'明细日志信息',
		height:'40%',
		width:'100%',
		columns:[{
			text:'序号',
			dataIndex:''
		},{
			text:'操作时间',
			dataIndex:''
		},{
			text:'动作',
			dataIndex:''
		}]
	}]
})