Ext.define('Wsitms.view.base.TableSpace',{
	extend:'Ext.panel.Panel',
	xtype:'table-space',
	layout:'vbox',//布局可以激活百分比
	requires: ['Wsitms.view.base.TaSpController'],
	controller: 'table-space',
	items:[{
		title:'数据库',
		xtype:'grid',
		style:'margin-top:2px',
		height:'60%',
		width:'100%',
		reference:'tableSpace',
		tbar:[{
			text:'数据库刷新',
			handler:''
		},{
			text:'查询表空间',
			handler:''
		}],
		columns:[{
			text:'实物编号',
			dataIndex:'ENTITYNO'
		},{
			text:'实物名称',
			dataIndex:'ENTITYNAME'
		}]
	},{
		xtype:'grid',
		title:'表空间',
		height:'40%',
		width:'100%',
		tbar:[{
			text:'保存',
			handler:''
		}],
		columns:[{
			text:'表空间名称',
			dataIndex:''
		},{
			text:'表空间大小M',
			dataIndex:''
		},{
			text:'已使用M',
			dataIndex:''
		},{
			text:'利用率',
			dataIndex:''
		}]
	}],
    listeners:{
    	afterlayout:{
    		fn:'onAfterLayout',
    		delay:1,
    		single:true//只执行一次
    	}
    },
})