Ext.define('Wsitms.view.base.UserForm',{
	extend:'Ext.window.Window',
	xtype:'user-form',
//	bind:{title:'{title}'},
	height:'500',
	width:400,
	bind:{
		title:'{title}'
	},
	modal:true,//模态框，开启遮罩
	items:{
	xtype:'form',
	reference:'userForm',
    layout:{
    	type:'vbox',
    	align:'center'
    },
	items:[{
		xtype:'textfield',
		fieldLabel:'用户ID',
		name:'USER_ID',
		hidden:true,		
		reference:'primary_id',
		bind:'{theUser.id}'
	},{
		xtype:'textfield',
		fieldLabel:'用户编号',
		name:'USER_CODE',
		allowBlank:false,
		blankText:'用户编号不能为空',
		msgTarget:'side',//设置不符合验证的提示方式
		bind:'{theUser.USER_CODE}'
	},{
		xtype:'textfield',
		fieldLabel:'用户名称',
		name:'USER_NAME',
		allowBlank:false,
		blankText:'用户名称不能为空',
		msgTarget:'side',
		bind:'{theUser.USER_NAME}'
	},{
		xtype:'textfield',
		fieldLabel:'用户类型',
		name:'USER_TYPE',
		allowBlank:false,
		blankText:'用户类型不能为空',
		msgTarget:'side',
		bind:'{theUser.USER_TYPE}'
	},{
		id:'newPwd',
		xtype:'textfield',
		fieldLabel:'登录密码',
		name:'PASSWD',
		msgTarget:'side',
		regex:/^((?=.*\d).{6,20})/,
		regexText:'密码必须有6-20的数字和密码组成',
		allowBlank : false ,
		blankText:'密码不能为空',
		inputType:'password',
		bind:'{theUser.PASSWD}'
	},{
		xtype:'textfield',
		fieldLabel:'确认密码',
		msgTarget:'side',
		vtype:'password',
		allowBlank : false ,
		blankText:'密码不能为空',
		inputType:'password',
	},{
		xtype:'datefield',
		fieldLabel:'有效开始日期',
		name:'VALID_SDATE',
		format: 'Y-m-d', 
		allowBlank:false,
		blankText:'有效日期不能为空',
		msgTarget:'side',
		bind:'{theUser.VALID_SDATE}',
	},{
		xtype:'datefield',
		fieldLabel:'有效结束日期',
		name:'VALID_TDATE',
		msgTarget:'side',
		format: 'Y-m-d', 
		allowBlank:false,
		blankText:'有效结束日期不能为空',
		bind:'{theUser.VALID_TDATE}'
	},{
		xtype:'textfield',
		fieldLabel:'有效标志',
		name:'VALID',
		bind:'{theUser.VALID}'
	},{
		xtype:'combobox',
		fieldLabel:'锁定用户',
		name:'LOCKED',
		bind:'{theUser.LOCKED}'
	},{
		xtype:'textarea',
		fieldLabel:'备注信息',
		name:'NOTE',
		bind:'{theUser.NOTE}'
	}],
	},
	buttons:[{
		text:'保存',
		handler:'saveForm'
	},{
		text:'清空',
		handler:'resetForm',
		reference:'userFormReset'
	},{
		text:'返回',
		handler:'closeForm'
	}]
})
Ext.apply(Ext.form.VTypes,{
	password:function(val,field){
		var pwd =Ext.getCmp('newPwd').getValue()
		if(val==pwd){
			return true;
		}
	},
       passwordText:'两次输入密码不一致！'
})



