Ext.define('Wsitms.view.define.SysCode',{
	extend:'Ext.panel.Panel',
	xtype:'sys-code',
	layout:'vbox',//布局可以激活百分比
	requires:[
		'Wsitms.view.define.SysCodeController',
		'Wsitms.view.define.SysCodeModel',
	],
	controller: 'sys-code',
	viewModel:{type:'sys-code'},
	items:[{
		title:'主代码信息',
		xtype:'grid',
		style:'margin-top:2px',
		height:'50%',
		width:'100%',
		bind:{store:'{sysCodeStore}'},
		tbar:[{
			text:'新增',
			handler:''
		},{
			text:'修改',
			handler:''
		},{
			text:'查询',
			handler:''
		}],
		columns:[{
			text:'主代码类型',
			dataIndex:'SYSTEMCODETYPE'
		},{
			text:'主代码名称',
			dataIndex:'SYSTEMCODENAME'
		},{
			text:'代码值类型',
			dataIndex:'SYSTEMCODEVALUETYPE'
		},{
			text:'修改标志',
			dataIndex:'CHANGEMARK'
		},{
			text:'备注',
			dataIndex:'NOTE'
		}],
		listeners:{
  			  rowclick:'rowclick'
  		    },
		bbar:{
		    xtype:'pagingtoolbar',
    	    displayInfo:true,//显示信息
    	    displayMsg : '显示:{0}-{1}条,总共:{2}条',//显示格式,0表示start 1表示end 2表示total
    	    emptyMsg:'没有需要显示的数据' 
		},
		selModel:{
			selType:'checkboxmodel'
		}
	},{
		xtype:'grid',
		title:'明细代码信息',
		height:'50%',
		width:'100%',
		reference:'syscodeinfo',
		tbar:[{
			text:'新增',
			handler:''
		},{
			text:'修改',
			handler:''
		},{
			text:'删除',
			handler:''
		}],
		columns:[{
			text:'代码值序列',
			dataIndex:'SYSTEMCODEVALUESEQ'
		},{
			text:'字符值',
			dataIndex:'SYSTEMCODECHAR'
		},{
			text:'数值',
			dataIndex:'SYSTEMCODENUMBER'
		},{
			text:'日期值',
			dataIndex:'SYSTEMCODEDATE'
		},{
			text:'值说明',
			dataIndex:'CODENOTE'
		}],
		selModel:{
			selType:'checkboxmodel'
		}
	}],
	listeners:{
    	afterlayout:{
    		fn:'onAfterLayout',
    		delay:1,
    		single:true//只执行一次
    	}
    }
})