Ext.define('Wsitms.view.system.ModuleForm',{
	extend:'Ext.window.Window',
	xtype:'module-form',
	height:'600',
	width:400,
	bind:{
		title:'{title}'
	},
	modal:true,//模态框，开启遮罩
	items:{
	xtype:'form',
	reference:'moduleForm',
    layout:{
    	type:'vbox',
    	align:'center'
    },
	items:[{
		xtype:'textfield',
		reference:'primary_id',
		fieldLabel:'模块ID',
		name:'MODULE_ID',
		hidden:true,
		bind:'{theModule.id}'
	},{
		xtype:'textfield',
		fieldLabel:'模块编号',
		name:'MODULE_CODE',
		allowBlank:false,
		blankText:'模块编号不能为空',
		msgTarget:'side',//设置不符合验证的提示方式
		bind:'{theModule.MODULE_CODE}'
	},{
		xtype:'textfield',
		fieldLabel:'模块名称',
		name:'MODULE_NAME',
		allowBlank:false,
		blankText:'模块名称不能为空',
		msgTarget:'side',
		bind:'{theModule.MODULE_NAME}'
	},{
		xtype:'textfield',
		fieldLabel:'模块注释',
		name:'MODULE_COMMENT',
		allowBlank:false,
		blankText:'模块注释不能为空',
		msgTarget:'side',
		bind:'{theModule.MODULE_COMMENT}'
	},{
		xtype:'textfield',
		fieldLabel:'模块组',
		name:'MODULE_GROUP',
		msgTarget:'side',
		allowBlank : false ,
		blankText:'模块组不能为空',
		bind:'{theModule.MODULE_GROUP}'
	},{
		xtype:'textfield',
		fieldLabel:'描述',
		msgTarget:'side',
		name:'DESCRIPTION',
		allowBlank : false ,
		blankText:'描述不能为空',
		bind:'{theModule.DESCRIPTION}'
	},{
		xtype:'datefield',
		fieldLabel:'有效开始日期',
		name:'UPDATETIME',
		format: 'Y-m-d', 
		allowBlank:false,
		blankText:'有效日期不能为空',
		msgTarget:'side',
		bind:'{theModule.UPDATETIME}',
	},{
		xtype:'textfield',
		fieldLabel:'有效结束日期',
		name:'VISIBLE',
		msgTarget:'side',
		format: 'Y-m-d', 
		allowBlank:false,
		blankText:'有效结束日期不能为空',
		bind:'{theModule.VISIBLE}'
	},{
		xtype:'textfield',
		fieldLabel:'有效标志',
		name:'VALID',
		msgTarget:'side',
		allowBlank:false,
		blankText:'有效标志不能为空',
		bind:'{theModule.VALID}'
	},{
		xtype:'textfield',
		fieldLabel:'图片地址',
		name:'ICON',
		msgTarget:'side',
		allowBlank:false,
		blankText:'图片地址不能为空',
		bind:'{theModule.ICON}'
	},{
		xtype:'textarea',
		fieldLabel:'版本',
		name:'MODULE_VERSION',
		msgTarget:'side',
		allowBlank:false,
		blankText:'版本不能为空',
		bind:'{theModule.MODULE_VERSION}'
	},{
		xtype:'textarea',
		fieldLabel:'模块类型',
		name:'MODULE_TYPE',
		msgTarget:'side',
		allowBlank:false,
		blankText:'模块类型不能为空',
		bind:'{theModule.MODULE_TYPE}'
	},{
		xtype:'textarea',
		fieldLabel:'注册人',
		name:'REGISTER',
		msgTarget:'side',
		allowBlank:false,
		blankText:'注册人不能为空',
		bind:'{theModule.REGISTER}'
	}],

	},
	buttons:[{
		text:'保存',
		handler:'saveForm'
	},{
		text:'清空',
		handler:'resetForm',
		reference:'resetForm',
	},{
		text:'返回',
		handler:'closeForm'
	}]
})


