Ext.define('Wsitms.view.system.RoleForm',{
	extend:'Ext.window.Window',
	xtype:'role-form',
	height:300,
	width:400,
	bind:{
		title:'{title}'
	},
	modal:true,//模态框，开启遮罩
	items:{
	xtype:'form',
	reference:'roleForm',
    layout:{
    	type:'vbox',
    	align:'center'
    },
	items:[{
		xtype:'textfield',
		fieldLabel:'角色ID',
		name:'ROLE_ID',
		hidden:true,
		reference:'primary_id',
		bind:'{id}'
	},{
		xtype:'textfield',
		fieldLabel:'角色编号',
		name:'ROLE_CODE',
		allowBlank:false,
		blankText:'角色编号不能为空',
		msgTarget:'side',//设置不符合验证的提示方式
	},{
		xtype:'textfield',
		fieldLabel:'角色名称',
		name:'ROLE_NAME',
		allowBlank:false,
		blankText:'角色名称不能为空',
		msgTarget:'side',
	},{
		xtype:'textarea',
		fieldLabel:'备注信息',
		name:'NOTE',
	}],
	},
	buttons:[{
		text:'保存',
		handler:'saveForm'
	},{
		text:'清空',
		handler:'resetForm',
		reference:'roleFormReset'
	},{
		text:'返回',
		handler:'closeForm'
	}]
})





