Ext.define("Wsitms.view.system.User",{
    extend: "Ext.grid.Panel",
    xtype: "user-manage",
    requires:[
    	'Wsitms.view.system.UserController',
    	'Wsitms.view.system.UserModel'
    ],  
    controller:'user-manage',
    viewModel:{type:'user-manage'},
    bind:{store:'{userStore}'},
    //顶部工具条
    layout:'fit',//适合容器内只有一个组件，拉伸至父容器最大
    title:'查询用户信息',
    tbar:[{
    	  text:'添加',
    	  tooltip:'添加用户信息',
    	  handler:'onAdd',
    	  glyph:0xf067
    },{
    	text:'修改',
    	tooltip:'修改用户信息',
    	handler:'onEdit',
    	glyph:0xf044
    },{
    	text:'查询',
    	tooltip:'查询用户信息',
    	handler:'',
        glyph:0xf010
    },{
        text:'设置用户权限',
        handler:'setAuthClick',
        glyph:0xf013
    }],    
    //列表字段
    columns:[{
    	text:'用户ID',
    	dataIndex:'USER_ID',
    	hidden:true,
    },{
    	text:'用户编号',
    	dataIndex:'USER_CODE',
    	align:'center',
    	sortable:false,
    },{
       text:'用户名称',
       dataIndex:'USER_NAME',
       flex:1
  
    },{
        text:'用户类型',
        dataIndex:'USER_ROLE',
        flex:1
    },{
        text:'密码',
        dataIndex:'PASSWD',
        hidden:true,
        flex:1  
     },{
    	 //xtype:"datecolumn",
        text:'有效开始日期',
        dataIndex:'VALID_SDATE',
        flex:1
    },{
    	//xtype:"datecolumn",renderer
        text:'有效结束日期',
        dataIndex:'VALID_TDATE',
        flex:1
    },{
        text:'有效标志',
        dataIndex:'VALID',
        hidden:true,
        flex:1
    },{
        text:'锁定用户',
        dataIndex:'LOCKED',
        hidden:true,
        flex:1
    },{
        text:'备注',
        dataIndex:'NOTE',
        flex:1
    }],    
    bbar:{
    	reference:'userpagingtoolbar',
    	bind:{
    		store:'{userStore}'
    	},
    	xtype:'pagingtoolbar',
    	displayInfo:true,
    	displayMsg:'显示:{0}-{1}条,总共:{2}条',
    	emptyMsg:'没有需要显示的数据'
    },
    //为每一条按钮添加勾选按钮
/*    selModel:{
    	selType:'checkboxmodel',
    },*/
   // renderTo:Ext.getBody(),容易破坏布局
   //加载数据
    listeners:{
    	afterlayout:{
    		fn:'onAfterLayout',
    		delay:1,
    		single:true//只执行一次
    	}
    },
    //listeners 配置多个会覆盖，注意
});

