Ext.define('Wsitms.model.Server',{
	extend:'Wsitms.model.Base',		
	fields:[{
		name:'SERVER_ID',type:'string'
	},{
		name:'CABINET',type:'string'
	},{
		name:'APPLICATION',type:'string'
	},{
		name:'SYS',type:'string'
	},{
		name:'NOTE',type:'string'
	},{
		name:'BRAND',type:'string'
	},{
		name:'IP',type:'string'
	}],
		
})